version: '2'

services:
  taiga:
    image: benhutchins/taiga
    ports:
      - 8080:80
      # - 443:443 # To enable SSL, uncomment this line
    # depends_on:
      # - postgres
    volumes:
      # I recommend specifying a volume that maps to taiga's media,
      # this way uploaded files are not lost during upgrades of the taiga image
      - /srv/media:/usr/src/taiga-back/media

      # If you'd like to store the configuration outside of the container,
      # uncomment this volume. This allows for easy changes to the configuration.
      # - /srv/conf/taiga:/taiga

      # - ./ssl.crt:/etc/nginx/ssl/ssl.crt:ro # To enable SSL, uncomment this line
      # - ./ssl.key:/etc/nginx/ssl/ssl.key:ro # To enable SSL, uncomment this line
    environment:
      # Your hostname (REQUIRED)
      TAIGA_HOSTNAME: localhost

      # Database settings
      # To use an external database, simply update these and remove the postgres
      # service from this docker-compose.yml file
      TAIGA_DB_NAME: taiga
      TAIGA_DB_HOST: 172.20.0.1
      TAIGA_DB_USER: postgres
      TAIGA_DB_PASSWORD: main5311
      TAIGA_SLEEP: 15 # when the db comes up from docker, it is usually too quick

      # TAIGA_SSL: True # To enable SSL, uncomment this line
      # TAIGA_SSL_BY_REVERSE_PROXY: True # To enable SSL, handling by a reverse proxy, uncomment this

      # To use an external SMTP for emails, fill in these values:
      # TAIGA_ENABLE_EMAIL: True
      # TAIGA_EMAIL_FROM: no-reply@taiga.mycompany.net
      # TAIGA_EMAIL_USE_TLS: True
      # TAIGA_EMAIL_HOST: smtp.google.com
      # TAIGA_EMAIL_PORT: 587
      # TAIGA_EMAIL_USER: me@gmail.com
      # TAIGA_EMAIL_PASS: super-secure-pass phrase thing!
    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.domain: app.spicter.com
      traefik.alias: pm
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - /srv/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.app.spicter.com
      - ADMIN_USERNAME=andreas
      - ADMIN_PASS=main5311
      - ADMIN_EMAIL=andreas@spicter.com
      - MONGO_URL=mongodb://172.20.0.1:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://172.20.0.1:27017/local
      - MAIL_URL=smtp://smtp.email
    ports:
      - 3000:3000
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.domain: app.spicter.com
      traefik.alias: chat
  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - /srv/scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080