version: '2'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:5.7
    labels:
      io.rancher.scheduler.affinity:host_label: mail_server=true
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
     - MYSQL_DATABASE=onlyoffice
     - MYSQL_USER=onlyoffice_user
     - MYSQL_PASSWORD=onlyoffice_pass 
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - /srv/mysql/config/mysql/conf.d:/etc/mysql/conf.d 
     - mysql_data:/var/lib/mysql
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:latest
    labels:
      io.rancher.scheduler.affinity:host_label: mail_server=true
      traefik.enable: true
      traefik.port: 80
      traefik.domain: app.spicter.com
      traefik.alias: office
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-document-server
     - onlyoffice-mail-server
    environment:
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice 
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server 
     - MYSQL_SERVER_USER=onlyoffice_user
     - MYSQL_SERVER_PASS=onlyoffice_pass 
     - MAIL_SERVER_API_PORT=8081
     - MAIL_SERVER_API_HOST=onlyoffice-mail-server
     - MAIL_SERVER_DB_HOST=onlyoffice-mysql-server
     - MAIL_SERVER_DB_PORT=3306
     - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
     - MAIL_SERVER_DB_USER=root
     - MAIL_SERVER_DB_PASS=my-secret-pw
    networks:
     - onlyoffice
    ports:
     - '80:80'
     - '443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - community_data:/var/www/onlyoffice/Data
     - community_log:/var/log/onlyoffice
     - document_data:/var/www/onlyoffice/DocumentServerData
     - /srv/community/certs:/var/www/onlyoffice/Data/certs
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    labels:
      io.rancher.scheduler.affinity:host_label: mail_server=true
      traefik.enable: true
      traefik.port: 80
      traefik.domain: app.spicter.com
      traefik.alias: docs
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
       - document_data:/var/www/onlyoffice/Data
       - /srv/document/document_fonts:/usr/share/fonts/truetype/custom
       - document_log:/var/log/onlyoffice
  onlyoffice-mail-server:
    container_name: onlyoffice-mail-server
    image: onlyoffice/mailserver:latest
    depends_on:
     - onlyoffice-mysql-server
    hostname: mail.spicter.net
    labels:
      io.rancher.scheduler.affinity:host_label: mail_server=true
    environment:
       - MYSQL_SERVER=onlyoffice-mysql-server
       - MYSQL_SERVER_PORT=3306
       - MYSQL_ROOT_USER=root
       - MYSQL_ROOT_PASSWD=my-secret-pw
       - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
    networks:
      - onlyoffice
    restart: always
    privileged: true
    ports: ['25:25','143:143','587:587']
    stdin_open: true
    tty: true
    expose:
      - '8081'
    volumes:
      - mail_data:/var/vmail
      - mail_certs:/etc/pki/tls/mailserver
      - mail_log:/var/log
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  mail_data:
  mail_certs:
  mail_log:
  document_data:
  document_log:
  community_data:
  community_log:
  mysql_data:
